/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye7374.views;

import edu.neu.csye7374.Apartment;
import edu.neu.csye7374.ApartmentAPI;
import edu.neu.csye7374.Broker;
import edu.neu.csye7374.Facade.ApartmentHandoverMethod;
import edu.neu.csye7374.Management;
import edu.neu.csye7374.Builder.BrokerBuilder;
import edu.neu.csye7374.Observer.ApartmentAgreement;
import edu.neu.csye7374.Strategy.OfferStrategy;
import edu.neu.csye7374.fileUtil.GeneralFileUtil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import javax.swing.JOptionPane;

public class AgreementSummary extends javax.swing.JPanel {
    private static AgreementSummary instance=null;
    private ApartmentAPI selectedApartment= null;
    private ApartmentAgreement currentAgreement= null;
    private String ORDERS_FILE_NAME = "AgreementsData.csv";
    private String EMP_FILE_NAME = "BrokerData.csv";
    private String MGMT_FILE_NAME = "MgmtData.csv";
    private MainFrame mainFrameRef;
    private Map<String, String> discountTypesNameMapping;
    private String[] discountTypeKeys;
    private List<Broker> brokerList;


    /**
     * Creates new form AgreementSummary
     */
    public AgreementSummary() {
        loadDefaults();
        initComponents();
    }
    
    public static AgreementSummary getInstance(){
        if(instance == null){
            instance= new AgreementSummary();
        }
        return instance;
    }

    private void loadDefaults(){
        this.discountTypesNameMapping = Map.of(
            "None", "None",
            "Student Discount", "StudentOfferStrategy",
            "Promotional Discount", "PromotionalStrategy", 
            "Family Discount", "FamilyOfferStrategy",
            "New Member Discount", "NewMemberOfferStrategy"
        );

        this.discountTypeKeys = new String[]{
            "None",
            "Student Discount", 
            "Family Discount",
            "New Member Discount",
            "Promotional Discount"
        };

        loadBrokers();

    }

    private void loadBrokers(){
        brokerList = new ArrayList<>();
        List<String> rawData = GeneralFileUtil.readFile(EMP_FILE_NAME);
        for (String line : rawData) {
            BrokerBuilder brokerBuilder = new BrokerBuilder(line);
            brokerList.add(brokerBuilder.build());
        }
    }

    private void saveBrokers(){
        StringBuilder res = new StringBuilder();
        for (Broker broker : brokerList) {
            res.append(broker.getId()+"," + broker.getFirstName() + "," + broker.getLastName() + "," + broker.getAge() + "," + broker.getWage() + "," + broker.getBonus()+"\n");
        } 
        GeneralFileUtil.writeFile(EMP_FILE_NAME, res.toString(), true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        apartmentAddress = new javax.swing.JLabel();
        apartmentCategory = new javax.swing.JLabel();
        apartmentMgmt = new javax.swing.JLabel();
        handoverMethod = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        handOverCost = new javax.swing.JLabel();
        agreementCost = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        discountTypes = new javax.swing.JComboBox<>();
        confirmAgreementBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        finalAgreementCost = new javax.swing.JLabel();
        offersAppliedLabel = new javax.swing.JLabel();
        offersApplied = new javax.swing.JLabel();
        selectBrokerLabel = new javax.swing.JLabel();
        brokerNames = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(793, 581));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agreement Summary");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Apartment Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Category");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Management");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Handover Method");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Discount Price");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Handover Cost");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Agreement Cost");

        offersAppliedLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        offersAppliedLabel.setText("Offers applied");

        selectBrokerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectBrokerLabel.setText("Select Broker");
        
        apartmentAddress.setText("Apartment Address");

        apartmentCategory.setText("Apartment Category");

        apartmentMgmt.setText("Mgmt");

        handoverMethod.setText("Handover Method");

        discount.setText("Disount Amount");

        handOverCost.setText("Delivery Cost");

        agreementCost.setText("Agreement Cost");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Discount Type");

        discountTypes.setModel(new javax.swing.DefaultComboBoxModel<>(this.discountTypeKeys));
        discountTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTypesActionPerformed(evt);
            }
        });

        brokerNames.setModel(new javax.swing.DefaultComboBoxModel<>(this.brokerList.stream().map(broker -> broker.getFirstName() + " " + broker.getLastName()).toArray(String[]::new)));

        confirmAgreementBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmAgreementBtn.setText("Confirm Agreement");
        confirmAgreementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmAgreementBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmAgreementBtnMouseExited(evt);
            }
        });
        confirmAgreementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAgreementBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Final Cost");

        finalAgreementCost.setText("Final Cost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartmentAddress)
                            .addComponent(apartmentCategory)
                            .addComponent(apartmentMgmt)
                            .addComponent(handoverMethod)))
                            .addComponent(offersAppliedLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(handOverCost))
                            .addComponent(confirmAgreementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(discountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectBrokerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(brokerNames, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(offersAppliedLabel)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finalAgreementCost)
                                    .addComponent(offersApplied)
                                    .addComponent(discount)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(agreementCost)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apartmentAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apartmentCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apartmentMgmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(handoverMethod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(agreementCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(handOverCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(discountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBrokerLabel)
                    .addComponent(brokerNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offersAppliedLabel)
                    .addComponent(offersApplied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(discount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(finalAgreementCost))
                .addGap(18, 18, 18)
                .addComponent(confirmAgreementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAgreementBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmAgreementBtnMouseEntered
        // TODO add your handling code here:
        confirmAgreementBtn.setBackground(new Color(0, 0, 0));
        confirmAgreementBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_confirmAgreementBtnMouseEntered

    private void confirmAgreementBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmAgreementBtnMouseExited
        // TODO add your handling code here:
        confirmAgreementBtn.setBackground(new Color(255, 255, 255));
        confirmAgreementBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_confirmAgreementBtnMouseExited

    private void confirmAgreementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAgreementBtnActionPerformed
        // TODO add your handling code here:
        this.currentAgreement.confirmAgreement();
        String[] selectedBrokerName = this.brokerNames.getSelectedItem().toString().split(" ");
        Broker selectedBroker = this.brokerList.stream()
                                    .filter(broker -> broker.getFirstName().equals(selectedBrokerName[0]) && broker.getLastName().equals(selectedBrokerName[1]))
                                    .findFirst()
                                    .get();
        selectedBroker.setBonus(selectedBroker.getBonus() + this.currentAgreement.runBonusStrategy());
        String lineToFile = this.apartmentAddress.getText() 
                            + "," + this.apartmentCategory.getText() 
                            + "," + this.apartmentMgmt.getText()
                            + "," + this.currentAgreement.getSaleType()
                            + "," + this.handoverMethod.getText()  
                            + "," + this.agreementCost.getText() 
                            + "," + this.handOverCost.getText()
                            + "," + this.discountTypesNameMapping.get(this.discountTypes.getSelectedItem().toString())
                            + "," + this.currentAgreement.getOfferDiscount()
                            + "," + this.finalAgreementCost.getText();
        GeneralFileUtil.writeFile(ORDERS_FILE_NAME, lineToFile, false);
        saveBrokers();
        modifyManagementData(this.apartmentMgmt.getText());
        JOptionPane.showMessageDialog(this, "Agreement Confirmed Successfully");
        this.mainFrameRef.getMainSplitPanel().setRightComponent(AgreementHistory.getInstance());
        this.discountTypes.setSelectedItem(0);
    }//GEN-LAST:event_confirmAgreementBtnActionPerformed

    private void modifyManagementData(String mgmtName){
        List<String> managementStrings = GeneralFileUtil.readFile(MGMT_FILE_NAME);
        List<Management> managements = managementStrings.stream().map(s -> {
            Management mg =  new Management();
            mg.setValues(s);
            return mg;
        }).toList(); 
        Management mgmt = managements.stream().filter(m -> m.getManagementName().equals(mgmtName)).findFirst().get();
        mgmt.setNoOfPropertiesSoldOrRented(mgmt.getNoOfPropertiesSoldOrRented() + 1);
        
        managementStrings = managements.stream().map(m -> m.toString()).toList();

        String finalString = String.join("\n", managementStrings);


        GeneralFileUtil.writeFile(MGMT_FILE_NAME, finalString, true);

    }

    private void discountTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTypesActionPerformed
        // TODO add your handling code here:
        String selectedValue =this.discountTypes.getSelectedItem().toString();
        System.out.println("Selected strategy: " + selectedValue);
        this.currentAgreement.setUsingStrategy(OfferStrategy.getOfferStrategyType(this.discountTypesNameMapping.get(selectedValue)));
        this.currentAgreement.runStrategy();
        this.discount.setText(Double.toString(this.currentAgreement.getOfferDiscount()));
        this.finalAgreementCost.setText(Double.toString(this.currentAgreement.getTotal()));
        this.offersApplied.setText(String.join(", ", this.currentAgreement.getOffersApplied()));
    }//GEN-LAST:event_discountTypesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apartmentCategory;
    private javax.swing.JLabel apartmentMgmt;
    private javax.swing.JLabel apartmentAddress;
    private javax.swing.JButton confirmAgreementBtn;
    private javax.swing.JLabel handoverMethod;
    private javax.swing.JLabel discount;
    private javax.swing.JComboBox<String> discountTypes;
    private javax.swing.JLabel finalAgreementCost;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel agreementCost;
    private javax.swing.JLabel handOverCost;
    private javax.swing.JLabel offersAppliedLabel;
    private javax.swing.JLabel offersApplied;
    private javax.swing.JLabel selectBrokerLabel;
    private javax.swing.JComboBox<String> brokerNames;
    
    // End of variables declaration//GEN-END:variables

    void setActiveApartment(ApartmentAPI selectedApartment) {
        this.selectedApartment= selectedApartment;
    }

    void setActiveAgreement(ApartmentAgreement currentAgreement) {
        this.currentAgreement= currentAgreement;
        loadDefaults();
    }

    void setLabelValues() {
        UUID apartmentId = this.selectedApartment.getApartmentId();
        ApartmentAPI sApartment= null;
        for(ApartmentAPI apartment:AddApartmentsPanel.getInstance().getApartmentList()){
            if(apartment.getApartmentId().equals(apartmentId)){
                sApartment=apartment;
            }
        }
        this.apartmentAddress.setText(sApartment.getApartmentAddress());
        this.apartmentCategory.setText(sApartment.getApartmentCategory().toString());
        String m= sApartment.getApartmentManagement().toString();
        this.apartmentMgmt.setText(m);
        this.handoverMethod.setText(this.currentAgreement.getApartmentHandoverMethod().toString());
        if(this.currentAgreement.getApartmentHandoverMethod() == ApartmentHandoverMethod.Digital){
            this.handOverCost.setText(Double.toString(this.currentAgreement.getHandoverCost()));
        }else{
            this.currentAgreement.setHandoverCost(0.0);
            this.handOverCost.setText(Double.toString(this.currentAgreement.getHandoverCost()));
        }
        this.discount.setText("Select Discount strategy above!");
        this.agreementCost.setText(Double.toString(this.currentAgreement.getApartmentAgreementCost()));
        this.finalAgreementCost.setText(Double.toString(this.currentAgreement.getTotal()));
        this.offersApplied.setText(String.join(", ", this.currentAgreement.getOffersApplied()));
    }
    
    void setMainFrame(MainFrame aThis) {
        this.mainFrameRef = aThis;
    }
}
